/**
 * The exact core, checked against an implementation that is not itself.
 *
 * Every other test in this repository was written by the same author as the
 * code it tests, at the same time, with the same idea of what the answer should
 * be. That shape of suite catches slips and cannot catch a misconception —
 * if I believed ties round half away from zero, I would have written the code
 * and the test to agree.
 *
 * `fixtures/oracle.json` is generated by `tools/oracle.py` from Python's
 * `fractions.Fraction` and `struct`: exact rational arithmetic and correctly
 * rounded binary64 conversion, implemented by other people, with different bugs.
 * Committed rather than run live, so this needs no Python in CI. Regenerate with
 * `python tools/oracle.py` and read the diff — a change means one of the two
 * implementations moved.
 *
 * The finite machines are checked here too, which took a second look. I had
 * written them off on the grounds that Python's unbounded integers hide
 * finiteness — true of an oracle that never asks, and wrong as a general claim.
 * Asked out loud they are the right tool: they quantize onto a Q128.128 or
 * 256-bit Planck grid exactly and then report whether the result fits the width,
 * which is a plain integer comparison. `Fraction` still does the part that is
 * hard to get right.
 *
 * What is still not offered is the overflow *policy* — checked, wrapping,
 * saturating. That is this project's design rather than a shared rule, and a
 * second implementation of it by the same author would be evidence of nothing.
 */

import { describe, expect, it } from 'vitest';
import oracle from '../../fixtures/oracle.json';
import {
  type Rational,
  ZERO,
  add,
  compare,
  div,
  equals,
  isZero,
  mul,
  rational,
  sub,
} from './rational/rational';
import { orderOfMagnitude10, orderOfMagnitude2 } from './rational/log10';
import { toExactDecimalString } from './rational/decimal';
import {
  bitsOf,
  encodeRational,
  isFiniteState,
  isNegativeZero,
  neighbors,
} from './representations/binary64';
import { Q128_128_PRESETS, encodeMeters as encodeQ128 } from './representations/q128_128';
import { encodeMeters as encodePlanck } from './representations/planck';
import { Q512_512, encode as encodeFixedPoint } from './representations/fixedPoint';
import { DIGIT_WIDTHS } from './wide/digits';
import { mulWide } from './wide/multiply';

const r = ([numerator, denominator]: string[]): Rational =>
  rational(BigInt(numerator!), BigInt(denominator!));

/** Enough cases that a passing run means something. */
const FLOOR = 250;

describe('exact arithmetic agrees with Python fractions', () => {
  it('was given cases to check', () => {
    expect(oracle.arithmetic.length).toBeGreaterThan(FLOOR);
    expect(oracle.generatorSha256).toHaveLength(64);
  });

  it('adds, subtracts, multiplies, divides and compares identically', () => {
    for (const entry of oracle.arithmetic) {
      const a = r(entry.a);
      const b = r(entry.b);
      const where = `${entry.a.join('/')} vs ${entry.b.join('/')}`;

      expect(add(a, b), `add ${where}`).toEqual(r(entry.add));
      expect(sub(a, b), `sub ${where}`).toEqual(r(entry.sub));
      expect(mul(a, b), `mul ${where}`).toEqual(r(entry.mul));
      expect(compare(a, b), `compare ${where}`).toBe(entry.compare);
      if (entry.div !== undefined) {
        expect(div(a, b), `div ${where}`).toEqual(r(entry.div));
      }
    }
  });
});

describe('order of magnitude agrees with exact integer comparison', () => {
  it('was given cases to check', () => {
    expect(oracle.magnitudes.length).toBeGreaterThan(FLOOR);
  });

  it('matches floor(log10) and floor(log2) on every value', () => {
    // Both sides compute these by comparison rather than by a logarithm, but
    // independently, and these inputs run from 10^-310 to 10^308.
    for (const entry of oracle.magnitudes) {
      const value = r(entry.value);
      expect(orderOfMagnitude10(value), `log10 of ${entry.value.join('/')}`).toBe(entry.log10);
      expect(orderOfMagnitude2(value), `log2 of ${entry.value.join('/')}`).toBe(entry.log2);
    }
  });
});

describe('exact decimal expansion agrees with Python', () => {
  it('was given cases to check', () => {
    expect(oracle.decimals.length).toBeGreaterThan(FLOOR);
    // Both outcomes must appear, or this only tests one branch.
    expect(oracle.decimals.some((entry) => entry.exactDecimal === null)).toBe(true);
    expect(oracle.decimals.some((entry) => entry.exactDecimal !== null)).toBe(true);
  });

  it('agrees on which fractions terminate, and on their digits', () => {
    for (const entry of oracle.decimals) {
      const actual = toExactDecimalString(r(entry.value));
      const expected = entry.exactDecimal ?? undefined;
      if (expected === undefined) {
        expect(actual, `${entry.value.join('/')} should repeat`).toBeUndefined();
      } else {
        // Python writes "0.5"; both sides must agree digit for digit.
        expect(actual, `${entry.value.join('/')}`).toBe(expected);
      }
    }
  });
});

describe('binary64 encoding agrees with correctly rounded conversion', () => {
  it('was given cases to check, including ties and subnormals', () => {
    expect(oracle.encodings.length).toBeGreaterThan(FLOOR);
    expect(oracle.encodings.some((entry) => entry.encoded.kind === 'zero')).toBe(true);
    expect(oracle.encodings.some((entry) => entry.encoded.kind === 'infinite')).toBe(true);
    expect(oracle.encodings.some((entry) => entry.encoded.kind === 'finite')).toBe(true);
  });

  it('produces the same bits, exact value and quantization error', () => {
    // `encodeRational` implements nearest-even by hand rather than delegating to
    // `Number(string)`. Python's `float(Fraction)` is the same rule implemented
    // by someone else, and the generated cases include values sitting exactly
    // half an ulp above a representable one — the input that separates
    // ties-to-even from ties-away-from-zero.
    for (const entry of oracle.encodings) {
      const value = r(entry.value);
      const encoded = encodeRational(value);
      const where = entry.value.join('/');

      if (entry.encoded.kind === 'infinite') {
        expect(isFiniteState(encoded.state), `${where} should overflow`).toBe(false);
        expect(encoded.overflowedToInfinity, where).toBe(true);
        continue;
      }

      if (entry.encoded.kind === 'zero') {
        expect(isFiniteState(encoded.state) && encoded.state.value === 0, where).toBe(true);
        if (isFiniteState(encoded.state)) {
          expect(isNegativeZero(encoded.state.value), `${where} sign of zero`).toBe(
            entry.encoded.negativeZero === true,
          );
        }
        expect(encoded.underflowedToZero, `${where} underflow`).toBe(
          entry.encoded.underflowed === true,
        );
        continue;
      }

      expect(isFiniteState(encoded.state), `${where} should be finite`).toBe(true);
      if (!isFiniteState(encoded.state)) continue;

      expect(bitsOf(encoded.state.value).toString(), `${where} bits`).toBe(entry.encoded.bits);
      expect(encoded.state.exact, `${where} exact value`).toEqual(r(entry.encoded.exact!));
      expect(encoded.quantizationError ?? ZERO, `${where} quantization`).toEqual(
        r(entry.encoded.quantizationError!),
      );
    }
  });

  it('rounds at least one tie, or it is not testing ties-to-even', () => {
    // A tie is the only input that separates the two rules, so the fixture has
    // to contain one that actually landed on a boundary.
    const tiesFound = oracle.encodings.filter((entry) => {
      if (entry.encoded.kind !== 'finite') return false;
      const stored = r(entry.encoded.exact!);
      const error = r(entry.encoded.quantizationError!);
      if (isZero(error)) return false;
      const gaps = neighbors(Number(stored.numerator) / Number(stored.denominator));
      const gap = gaps.gapAbove ?? gaps.gapBelow;
      return gap !== undefined && equals(mul(add(error, error), rational(1n)), gap);
    });
    expect(tiesFound.length, 'no tie in the fixture').toBeGreaterThan(0);
  });
});

describe('the finite machines quantize where Python says they do', () => {
  it('was given cases to check, on both sides of every boundary', () => {
    expect(oracle.q128.length).toBeGreaterThan(FLOOR);
    expect(oracle.planck.length).toBeGreaterThan(FLOOR);
    expect(oracle.errorMeter.length).toBeGreaterThan(FLOOR);
    // Both outcomes must appear or only one branch is under test.
    expect(oracle.q128.some((entry) => entry.fits)).toBe(true);
    expect(oracle.q128.some((entry) => !entry.fits)).toBe(true);
    expect(oracle.planck.some((entry) => !entry.fits)).toBe(true);
  });

  it('stores the same raw register at every base unit, or refuses', () => {
    // The width question is asked explicitly on the Python side, so this is a
    // real comparison rather than an unbounded integer agreeing with itself.
    for (const entry of oracle.q128) {
      const config = Q128_128_PRESETS[entry.baseUnit as keyof typeof Q128_128_PRESETS];
      const value = r(entry.value);
      const write = encodeQ128(config, value);
      const where = `${entry.value.join('/')} @ ${entry.baseUnit}`;

      if (!entry.fits) {
        expect(write.status, `${where} should be refused`).toBe('rejected');
        expect(write.state, where).toBeUndefined();
        continue;
      }

      expect(write.status, where).toBe('stored');
      expect(write.state?.raw.toString(), `${where} raw`).toBe(entry.raw);
      expect(write.decodedMeters, `${where} decoded`).toEqual(r(entry.decoded!));
      expect(write.quantizationErrorMeters, `${where} quantization`).toEqual(
        r(entry.quantizationError!),
      );
    }
  });

  it('counts the same Planck ticks', () => {
    for (const entry of oracle.planck) {
      const value = r(entry.value);
      const write = encodePlanck(value);
      const where = entry.value.join('/');

      if (!entry.fits) {
        expect(write.status, `${where} should be refused`).toBe('rejected');
        continue;
      }
      expect(write.state?.ticks.toString(), `${where} ticks`).toBe(entry.ticks);
      expect(write.decoded, `${where} decoded`).toEqual(r(entry.decoded));
    }
  });

  it('fills the Q512.512 error meter to the same raw value', () => {
    for (const entry of oracle.errorMeter) {
      if (!entry.fits) continue;
      const value = r(entry.value);
      const write = encodeFixedPoint(Q512_512, value, 'nearest-even', 'checked');
      const where = entry.value.join('/');
      expect(write.state?.raw.toString(), `${where} raw`).toBe(entry.raw);
      expect(write.decoded, `${where} decoded`).toEqual(r(entry.decoded!));
    }
  });

  it('agrees on ties, which is the whole reason to check quantization', () => {
    // Exactly half an LSB is the only input that separates nearest-even from
    // half-away-from-zero, and the fixture is generated to contain some.
    const halfLsb = oracle.q128.filter(
      (entry) => entry.fits && entry.quantizationError !== undefined,
    );
    expect(halfLsb.length).toBeGreaterThan(FLOOR);
  });
});

describe('MUL_WIDE agrees with the CPU oracle, as §19 requires', () => {
  it('was given cases to check, including the ones §19 names', () => {
    expect(oracle.wideMultiply.length).toBeGreaterThan(100);
    // All-ones against all-ones is the longest carry chain available.
    const allOnes = ((1n << 1024n) - 1n).toString();
    expect(oracle.wideMultiply.some((entry) => entry.a === allOnes || entry.b === allOnes)).toBe(
      true,
    );
    expect(oracle.wideMultiply.some((entry) => entry.a.startsWith('-'))).toBe(true);
    expect(oracle.wideMultiply.some((entry) => entry.product === '0')).toBe(true);
  });

  it('produces the same product at every digit width', () => {
    // The simulator accumulates digit by digit and never multiplies the whole
    // values; Python does the opposite. Agreement across five slice widths is
    // the check §19 asks for, and the slice width must not change the answer.
    for (const entry of oracle.wideMultiply) {
      const a = BigInt(entry.a);
      const b = BigInt(entry.b);
      const expected = BigInt(entry.product);
      for (const digitBits of DIGIT_WIDTHS) {
        expect(
          mulWide(a, b, { digitBits, registerBits: 1024 }).value,
          `${entry.a} × ${entry.b} at ${digitBits}-bit digits`,
        ).toBe(expected);
      }
    }
  });

  it('needs no more than double width, whatever the operands', () => {
    for (const entry of oracle.wideMultiply) {
      expect(entry.productBits, `${entry.a} × ${entry.b}`).toBeLessThanOrEqual(2048);
    }
  });
});

describe('binary64 neighbours agree with math.nextafter', () => {
  it('was given cases to check', () => {
    expect(oracle.neighbourhoods.length).toBeGreaterThan(FLOOR);
  });

  it('walks to the same neighbours and reports the same gaps', () => {
    for (const entry of oracle.neighbourhoods) {
      const stored = r(entry.value);
      const encoded = encodeRational(stored);
      if (!isFiniteState(encoded.state)) continue;
      const report = neighbors(encoded.state.value);
      const where = entry.value.join('/');

      if (entry.gapBelow !== undefined) {
        expect(report.gapBelow, `${where} gap below`).toEqual(r(entry.gapBelow));
      }
      if (entry.gapAbove !== undefined) {
        expect(report.gapAbove, `${where} gap above`).toEqual(r(entry.gapAbove));
      }
    }
  });
});
